// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> ar = {
    "have_no_account": "ليس لديك حساب؟",
    "welcom_mazzoon1": "مرحبا بك في تطبيق مأذون",
    "welcom_mazzoon2": "الشريك الموثوق لحفل زفافك",
    "welcom_mazzoon3": "من فضلك ادخل البيانات التالية لانشاء حسابك",
    "welcom_mazzoon4": "بتسجيلك للدخول فأنت توافق على الشروط والأحكام",
    "welcom_mazzoon5": "من فضلك ادخل رقم الجوال لارسال الرمز ",
    "welcom_mazzoon6": "لقد أرسلنا لك رسالة نصية قصيرة مكونة من 6 أرقام",
    "welcom_mazzoon7": "ارسل مرة اخرى",
    "welcom_mazzoon8": "لم يتم الاستلام",
    "welcom_mazzoon10": "ادخل كلمة مرور جديدة",
    "welcom_mazzoon11": "اعد ادخال كلمة المرور",
    "welcom_mazzoon12": "قم بادخال كلمة المرور الجديدة",
    "welcom_mazzoon13": "تم تعديل كلمة المرور بنجاح",
    "welcom_mazzoon14": "تم انشاء حسابك بنجاح",
    "have_account": "لديك حساب؟",
    "login_now": "سجل الدخول الان",
    "phone": "رقم الجوال",
    "forget_password1": "نسيت كلمة المرور ؟",
    "forget_password2": "نسيت كلمة المرور",
    "password": "كلمة المرور",
    "signup_button": "انشاء حساب جديد",
    "login_button": "تسجيل الدخول",
    "full_name": "اسم المستخدم",
    "email": "البريد الالكتروني",
    "iD_number": "رقم الهوية",
    "confirm_passowrd": "تأكيد كلمة المرور",
    "reset_passowrd": "إعادة تعيين كلمة المرور",
    "forget_message":
        "ستتلقى بريدًا إلكترونيًا لإعادة تعيين كلمة المرور الخاصة بك",
    "my_profile": "حسابي",
    "log_out": "تسجيل خروج",
    "profile": "الملف الشخصي",
    "name": "الاسم",
    "contact_us": "تواصل معنا",
    "about_us": "من نحن",
    "terms_conditions": "الأحكام والشروط",
    "privacy_policy": "سياسة الخصوصية",
    "send": "ارسال",
    "next": "التالي",
    "home": "الرئيسية",
    "send_code": "ارسل الرمز",
    "check": "تحقق",
    "save": "حفظ",
    "ok": "حسنا",
    "search": "ابحث",
    "recommen_mazzoon": "رشح لي مأذون",
    "high_rate": "اعلى تقييما",
    "more": "المزيد",
    "my_reservation": "حجوزاتي",
    "suggested_mazzoon": "مأذون مقترح",
    "edit_password_done": "تم تعديل كلمة المرور بنجاح",
    "my_wallet": "محفظتي",
    "about_mazzoon": "عن مأذون",
    "common_questions": "الاسئلة الشائعة",
    "location_map": "خريطة الموقع",
    "settings": "الاعدادات",
    "share_app": "شارك التطبيق",
    "join_to_mazzoon": "انظم الى قائمة المأذونين",
    "lang": "اللغة",
    "notification": "الإشعارات",
    "logout": "تسجيل الخروج",
    "more_title": "هذا التطبيق موثق من وزارة ",
    "more_title1": "التجارة السعودية",
    "map": "الخريطة",
    "filter": "التصفية",
    "place": "المكان",
    "day": "اليوم",
    "watch": "الساعة",
    "mazzoon": "المأذون",
    "choose_place_quran": "اختر مكان عقد القران",
    "conutry": "البلد",
    "city": "المدينة",
    "street": "الحى",
    "address": "العنوان",
    "back": "الرجوع",
    "confirm_place": "تأكيد مكان",
    "legitimate_mazzoon": "مأذون شرعي",
    "reservation_mazzoon": "حجز المأذون",
    "marriage_number": "رقم طلب الزواج",
    "choose_place": "اختر المكان",
    "wedding_day": "مكان الزواج",
    "choose_time": "اختر الوقت",
    "pay_to_mazzoon": "ادفع للمأذون(اختيارى)",
    "num_ministry_of_Justice": "ادخل الرقم المزود من وزارة العدل",
    "search_place": "البحث عن مكان",
    "choose_day": "اختر يوم",
    "enter_amount": "ادخل مبلغ من 500 ر.س الى 2500 ر.س",
    "payment_method": "طريقة الدفع",
    "visa": "فيزا",
    "master": "ماستر كارد",
    "apple_pay": "أبل باي",
    "stc": "اس تي سي باي",
    "wallet": "المحفظة",
    "list": "ليستة",
    "50 Sar": "50 ريال سعودي",
    "via": "هذا المبلغ رسوم الحجز عن طريق  التطبيق",
    "filter_by-place": "تصفية حسب المكان",
    "filter_by-rate": "تصفية حسب التقييم",
    "filter_by-day": "حسب اليوم المتاح",
    "filter_by-time": "حسب الساعة المتاحة",
    "filter_result": "تصفية النتائج",
    "Choose_the_right_ma'zoun": "اختر المأذون المناسب لك",
    "am": "مساءا",
    "pm": "صباحا",
    "confirm": "تأكيد",
    "otp1": "رمز OTP",
    "reservation_confirm": "تأكيد الحجز",
    "reservation_details": "تفاصيل الحجز",
    "choose_ma'zoun": "اختيار الماذون",
    "offer_accepted": "تم قبول العرض",
    "request_accepted": "تم قبول الطلب",
    "details": "التفاصيل",
    "wait_accepted": "في انتظار موافقة المأذون",
    "apologized_not_attending": "المأذون اعتذر عن الحضور",
    "the_request_done": "تم تنفيذ الطلب",
    "report_ma'zoun": "الابلاغ عن المأذون",
    "welcom_mazzoon15": "كلمة المرور الحالية",
    "rate_ma'zoun": "تقييم المأذون",
    "cancel_request": "الغاء الطلب",
    "switch_ma'zoun": "استبدال المأذون",
    "switch_ma'zoun1": "تبديل المأذون",
    "edit_request": "التعديل على الطلب",
    "edit_request1": "تعديل الطلب",
    "rate_experience": "قييم تجربتك",
    "how_experience": "كيف كانت تجربتك",
    "srend_rate": "ارسال التقيم",
    "call_us": "تواصل هاتفيا",
    "resaon_report": "سبب الإبلاغ ",
    "send_report": "ارسال البلاغ",
    "report_details": "تفاصيل البلاغ",
    "request_details": "تفاصيل الطلب",
    "choose_reason": "اختر السبب",
    "sure_reaport": "هل انت متأكد من الإبلاغ عن الشيخ مشعل بن عبدالعزيز؟",
    "scan_not_back": "لا يمكن الرجوع بعد هذه الخطوة",
    "recommend_ma'zoun": "الشيخ مشعل رشح لك بديل",
    "sure_cancel": "هل انت متأكد من إلغاء الطلب؟",
    "sure_cancel1": "تأكيد الإلغاء",
    "send_rate_done": "تم ارسال تقيمكم بنجاح",
    "edites_done": "تم حفظ التعديلات بنجاح",
    "send_report_done": "تم ارسال الشكوى بنجاح وسيتم مرجعتها واتخاذ ما يلزم",
    "cancel_done":
        "تم الغاء طلبكم بنجاح وسيتم رد رسوم التطبيق الى المحفظة الخاصة بكم قريبا",
    "current_money": "الرصيد الحالي",
    "pull_money": "سحب الاموال",
    "num_money": "طلب رقم 1341",
    "210 Sar": "+210 ر.س",
    "edit_phone": "تعديل رقم الهاتف",
    "save_edites": "حفظ التعديلات",
    "change_photo": "تغيير الصورة الشخصية",
    "type_message": "اكتب الرسالة هنا",
    "change_password": "تغيير كلمة المرور",
    "join_now": "يمكنك الإنضمام الى قائمة المأذونين الآن!",
    "edit_data": "تعديل المعلومات الشخصية",
    "download_app": "حمل تطبيق المأذونين الآن لتبدأ استقبال الطلبات",
    "download_app1": "تحميل التطبيق",
    "join_now2": "انضم الينا",
    "mazzoon_name": "اسم المأذون",
  };
  static const Map<String, dynamic> en = {
    "mazzoon_name": "Ma'zoun Name",
    "have_no_account": "You don't have an account?",
    "welcom_mazzoon1": "Welcome to Ma'zoun App",
    "welcom_mazzoon2": "The reliable partner for your wedding",
    "welcom_mazzoon3":
        "Please enter the following information to create your account.",
    "welcom_mazzoon4": "By logging in, you agree to the Terms and Conditions",
    "welcom_mazzoon5": "Please enter your mobile number to send the code.",
    "welcom_mazzoon6": "We have sent you a 6-digit SMS",
    "welcom_mazzoon7": "Resend",
    "welcom_mazzoon8": "Not received",
    "welcom_mazzoon10": "Enter a new password",
    "welcom_mazzoon11": "Re-enter password",
    "welcom_mazzoon12": "Enter the new password",
    "welcom_mazzoon13": "Password modified successfully",
    "welcom_mazzoon14": "Your account has been created successfully.",
    "have_account": "you have an account?",
    "login_now": "Log in now",
    "confirm": "Confirm",
    "otp1": "OTP Code",
    "phone": "Mobile number",
    "forget_password1": "Forgot your password ?",
    "forget_password2": "Forgot your password",
    "password": "Password",
    "signup_button": "Create a new account",
    "login_button": "Sign in",
    "full_name": "User name",
    "email": "E-mail",
    "iD_number": "ID Number",
    "confirm_passowrd": "Confirm password",
    "reset_passowrd": "Password Reset",
    "forget_message": "You will receive an email to reset your password.",
    "my_profile": "My Profile",
    "log_out": "Log out",
    "profile": "Profile",
    "name": "Name",
    "contact_us": "Contact With us",
    "about_us": "About us",
    "terms_conditions": "terms and conditions",
    "privacy_policy": "privacy policy",
    "send": "Send",
    "next": "Next",
    "home": "Home",
    "send_code": "Send Code",
    "check": "Check",
    "save": "Save",
    "ok": "Ok",
    "search": "Search",
    "recommen_mazzoon": "Recommended Ma'zoun",
    "high_rate": "Highest rated",
    "more": "  More  ",
    "my_reservation": "  My Reservation  ",
    "suggested_mazzoon": "suggestion Ma'zoun",
    "edit_password_done": "Password modified successfully",
    "my_wallet": "My wallet",
    "about_mazzoon": "About Ma'zoun",
    "common_questions": "Common questions",
    "location_map": "Site Map",
    "settings": "Settings",
    "share_app": "Share app",
    "join_to_mazzoon": "Join to Ma'zounes List",
    "lang": "Language",
    "notification": "Notification",
    "logout": "Logout",
    "more_title": "This app certified ",
    "more_title1": "by Saudi Ministry of Commerce",
    "map": "Map",
    "filter": "Filter",
    "place": "Place",
    "day": "Day",
    "watch": "Time",
    "mazzoon": "Ma'zoun",
    "choose_place_quran": " Marriage contract",
    "conutry": "Country",
    "city": "City",
    "street": "District",
    "address": "Address",
    "back": "Back",
    "confirm_place": "confirm place",
    "legitimate_mazzoon": "official Ma'zoun",
    "reservation_mazzoon": "Reservation Ma'zoun",
    "marriage_number": "Marriage application number",
    "choose_place": "Choose place",
    "wedding_day": "The Day of the Wedding",
    "choose_time": "Choose time",
    "pay_to_mazzoon": "pay to ma'zoun (optional)",
    "num_ministry_of_Justice":
        "Enter the number provided by the Ministry of Justice",
    "search_place": "Find a place",
    "choose_day": "Choose day",
    "enter_amount": "Enter an amount from 500 SAR to 2500 SAR",
    "payment_method": "Payment method",
    "visa": "Visa",
    "master": "Master Card",
    "apple_pay": "Apple pay",
    "stc": "stc",
    "wallet": "Wallet",
    "list": "List",
    "50 Sar": "50 SAR",
    "via": "This amount is the reservation fee through the application.",
    "filter_by-place": "Filter by location",
    "filter_by-rate": "Filter by rate",
    "filter_by-day": "Filter by available day",
    "filter_by-time": "Filter by available time",
    "filter_result": "Filter results",
    "Choose_the_right_ma'zoun": "Choose the right Ma'zoun for you",
    "am": "Pm",
    "pm": "Am",
    "reservation_confirm": "reservation confirm",
    "reservation_details": "Reservation details",
    "choose_ma'zoun": "Choose Ma'zoun",
    "offer_accepted": "Offer accepted",
    "request_accepted": "Request accepted",
    "details": "Details",
    "wait_accepted": "Awaiting the approval of Ma'zoun",
    "apologized_not_attending": "Ma'zoun apologized for not attending",
    "the_request_done": "Request Done",
    "report_ma'zoun": "Reporting to the Ma'zoun",
    "rate_ma'zoun": "Ratting to the Ma'zoun",
    "cancel_request": "Cancel request",
    "switch_ma'zoun": "Switch Ma'zoun",
    "switch_ma'zoun1": "Switch Ma'zoun",
    "edit_request": "Edit request",
    "edit_request1": "Edit request",
    "rate_experience": "Rate your experience",
    "how_experience": "How was your experience",
    "srend_rate": "Send Rate",
    "call_us": "Phone call",
    "resaon_report": "Reason for reporting",
    "send_report": "Send report",
    "report_details": "Report details",
    "request_details": "Request details",
    "choose_reason": "Choose reason",
    "sure_reaport": "Are you sure to report Sheikh Mishaal bin Abdulaziz?",
    "scan_not_back": "can not turning back after this step.",
    "recommend_ma'zoun": "Sheikh Mishaal recommended you an alternative.",
    "sure_cancel": "Are you sure to cancel the request?",
    "sure_cancel1": "cancel confirm",
    "welcom_mazzoon15": "Current Password",
    "send_rate_done": "Your review has been sent successfully",
    "edites_done": "Modifications saved successfully",
    "send_report_done":
        "The complaint has been sent successfully, and it will be reviewed and necessary action will be taken.",
    "cancel_done":
        "Your request has been successfully canceled and the application fee will be refunded to your wallet soon",
    "current_money": "current balance",
    "pull_money": "cash withdrawal",
    "num_money": "Request No. 1341",
    "210 Sar": "+210 SAR",
    "edit_phone": "Modify phone number",
    "save_edites": "save edits",
    "change_photo": "change profile picture",
    "type_message": "Type message here",
    "change_password": "change password",
    "join_now": "You can join the ma'zounes list now!",
    "edit_data": "Edit personal information",
    "download_app":
        "Download the ma'zoun application now to start receiving requests",
    "download_app1": "Download app",
    "join_now2": "Join us"
  };

  static const Map<String, Map<String, dynamic>> mapLocales = {
    "en": en,
    "ar": ar,
    // "tr": tr,
  };
}
